from listaCircular import listaCircular
print('___________________________________')
print("         TAREA 2")
lista = listaCircular()
lista.insertar(5)
lista.insertar(22)
lista.insertar(1)
lista.insertar(3)
lista.insertar(9)
lista.insertar(98)
lista.insertar(102)
lista.imprimir()
print("NUMERO SELECCIONADO: 5 ")
lista.buscar(5)
